### ISSUE TITLE
Can't deploy the SAR package ServiceCloudVoiceLambdas — version 9.0.1

### ISSUE THREAD

**Issue by sonymammen-vf** [service-cloud-voice/ServiceCloudVoiceLambdas#11] opened 2022-07-28 02:16 UTC
Faced this issue in multiple AWS accounts. The SAR deployment attempt is sitting on the initial screen and spinning for hours. No error message shown on the screen. 

![SAR error](https://user-images.githubusercontent.com/78828351/181405572-1cd62a8f-4165-4ced-b22d-c7a596136614.png)

Copied an already deployed SAR CFN and attempted it from a different account and got the below error message. But that could be an entirely different access issue. Not sure if below permission error is happening when we deploy from the SAR UI as well. 

**_Your access has been denied by S3, please make sure your request credentials have permission to GetObject for awsserverlessrepo-changesets-1my58927y6rqa/765230478770/arn:aws:serverlessrepo:us-east-1:317368162107:applications-ServiceCloudVoiceLambdas-versions-2.0.1/43c8d247-0584-43d2-a395-98191089e900. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: c58d5d7d-6842-4a1f-8c58-5a07f200af89; Proxy: null)_**

**Comment by sonymammen-vf** [comment] 2022-08-02 04:28
Confirmed the issue to be in ap-southeast-2. Deployed in us-east-1 without any issue. Awaiting a fix.

**Comment by safamoha** [comment] 2022-08-04 04:54
Hi, I’m from the AWS SAR team and we have been seeing a few issues with deployment of this specific application over the past few weeks. 

It looks like one of your application assets is of a size larger than we are used to handling. We are determining a fix for this issue on our end.

**Comment by jinalkathiara** [comment] 2022-08-04 21:40
Thank you @safamoha. Can you post any ETA once the issue is resolved ?

**Comment by safamoha** [comment] 2022-08-05 18:55
On our end we are seeing the issue in FRA, NRT, and SYD regions. We are aiming to get the fix deployed to FRA by end of next week. Should the fix work as intended, we can deploy to other regions by end of the following week.

**Comment by magnetikonline** [comment] 2022-08-08 01:15
@safamoha adding a comment in here for updates to this issue for myself.

**Comment by jono-ak** [comment] 2022-08-15 04:41
This is a critical issue for us too. Our LAMBDA is requiring an update an we urgently need this fix to be able to update. @safamoha 
Did the FRA release work last week and can we expect a fix for SYD region this week?

**Comment by jinalkathiara** [comment] 2022-08-23 06:41
@jono-ak @safamoha @sonymammen-vf @magnetikonline  -- Can you try this on your end ? 

This issue should be fixed by the AWS deployment team.

**Comment by safamoha** [comment] 2022-08-29 16:59
On our end the issue appears to be fixed. Please let us know if you are seeing otherwise.

**Comment by jinalkathiara** [comment] 2022-08-29 18:05
@safamoha We also verified this issue on our end and the issue is fixed. I was just giving a heads up to other customers who got affected. Closing this issue now. 
Thanks for your help @safamoha

**Closed by jinalkathiara** 2022-08-29 18:05 UTC
